#!/usr/bin/env python3
"""Regenerate `openbim-dt/src/schema.rs` from a derived structural catalog.

The catalog is a structural summary (element names, cardinalities, datatype
facets) derived from a legally accessed local copy of the ISO 23387 schema.
Neither the schema nor its prose is read, vendored, or reproduced here: the
generated tables contain only the grammar facts needed to validate instances.

Usage:
    generate-schema-tables.py <catalog.json> [output.rs]
    cargo fmt --all

The committed `schema.rs` is exactly this script's output followed by
`cargo fmt`; the raw output is deterministic across runs.

The catalog path is a required argument and is deliberately *not* defaulted to
any developer-specific location, so this script is runnable on any host.
"""

import json
import pathlib
import sys

if len(sys.argv) < 2:
    sys.exit(__doc__.strip())

CAT = sys.argv[1]
REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = sys.argv[2] if len(sys.argv) > 2 else str(REPO / "openbim-dt" / "src" / "schema.rs")
cat = json.load(open(CAT, encoding="utf-8"))
els = cat["elements"]

# Resolve xs:* facets by walking a type's base_type chain.
def resolve(handle, key):
    seen = set()
    while handle and handle in els and handle not in seen:
        seen.add(handle)
        v = els[handle].get(key)
        if v:
            return v
        handle = els[handle].get("base_type")
    return None

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

# The catalog already flattens xs:extension into each type's own children,
# attributes, and choice groups. Walking base_type here would duplicate every
# inherited particle and split one choice group into two.
def all_children(handle):
    return els[handle].get("children") or []

def all_attributes(handle):
    return els[handle].get("attributes") or []

# A "definition" is any type/element handle we must emit a rule for.
# Seed from the six global roots, then close over child definitions.
roots = sorted(cat["global_elements"])
wanted, queue = set(), []
for r in roots:
    d = els.get(r) or {}
    target = d.get("data_type") if (d.get("data_type") in els) else r
    queue.append(target)
while queue:
    h = queue.pop()
    if h in wanted or h not in els:
        continue
    wanted.add(h)
    b = els[h].get("base_type")
    if b:
        queue.append(b)
    for c in all_children(h):
        dfn = c.get("definition")
        if dfn in els:
            queue.append(dfn)

defs = sorted(wanted)
index = {h: i for i, h in enumerate(defs)}
print("definitions:", len(defs))

L = []
w = L.append
w("//! ISO 23387 schema tables. GENERATED FILE - DO NOT EDIT BY HAND.")
w("//!")
w("//! Regenerated by `scripts/generate-schema-tables.py` from a derived")
w("//! structural catalog. No normative schema text, documentation, or annex")
w("//! example is reproduced here: only element/attribute names, cardinalities,")
w("//! and the datatype facets required to validate an instance document.")
w("")
w("/// A child edge: which definition it points at and how often it may occur.")
w("#[derive(Debug, Clone, Copy)]")
w("pub(crate) struct ChildRule {")
w("    pub(crate) name: &'static str,")
w("    pub(crate) definition: usize,")
w("    pub(crate) min_occurs: u32,")
w("    /// `None` encodes `unbounded`.")
w("    pub(crate) max_occurs: Option<u32>,")
w("    /// Index into [`Definition::choice_groups`], when this edge is a branch.")
w("    pub(crate) choice_group: Option<usize>,")
w("}")
w("")
w("/// An attribute declaration with its lexical constraints.")
w("#[derive(Debug, Clone, Copy)]")
w("pub(crate) struct AttributeRule {")
w("    pub(crate) name: &'static str,")
w("    pub(crate) required: bool,")
w("    pub(crate) data_type: &'static str,")
w("    pub(crate) pattern: Option<&'static str>,")
w("    pub(crate) enum_values: &'static [&'static str],")
w("}")
w("")
w("/// A repeating choice: at least `min_occurs` of `members` must appear.")
w("#[derive(Debug, Clone, Copy)]")
w("pub(crate) struct ChoiceGroup {")
w("    pub(crate) min_occurs: u32,")
w("    pub(crate) max_occurs: Option<u32>,")
w("    pub(crate) members: &'static [&'static str],")
w("}")
w("")
w("/// One complex or simple type definition.")
w("#[derive(Debug, Clone, Copy)]")
w("pub(crate) struct Definition {")
w("    pub(crate) handle: &'static str,")
w("    pub(crate) children: &'static [ChildRule],")
w("    pub(crate) attributes: &'static [AttributeRule],")
w("    pub(crate) choice_groups: &'static [ChoiceGroup],")
w("    /// Simple-content datatype, when the definition carries text.")
w("    pub(crate) data_type: Option<&'static str>,")
w("    pub(crate) pattern: Option<&'static str>,")
w("    pub(crate) enum_values: &'static [&'static str],")
w("}")
w("")

def opt_str(v):
    return 'Some("%s")' % esc(v) if v else "None"

def occurs(v):
    return "None" if v is None else "Some(%d)" % int(v)

w("pub(crate) static DEFINITIONS: &[Definition] = &[")
for h in defs:
    d = els[h]
    groups = d.get("choice_groups") or []
    gidx = {g["handle"]: i for i, g in enumerate(groups)}
    w("    Definition {")
    w('        handle: "%s",' % esc(h))
    kids = all_children(h)
    if not kids:
        w("        children: &[],")
    else:
        w("        children: &[")
        for c in kids:
            dfn = c.get("definition")
            if dfn not in index:
                continue
            w("            ChildRule {")
            w('                name: "%s",' % esc(c["name"]))
            w("                definition: %d," % index[dfn])
            w("                min_occurs: %d," % int(c.get("min_occurs") or 0))
            w("                max_occurs: %s," % occurs(c.get("max_occurs")))
            cg = c.get("choice_group")
            w("                choice_group: %s," % ("Some(%d)" % gidx[cg] if cg in gidx else "None"))
            w("            },")
        w("        ],")
    attrs = all_attributes(h)
    if not attrs:
        w("        attributes: &[],")
    else:
        w("        attributes: &[")
        for a in attrs:
            w("            AttributeRule {")
            w('                name: "%s",' % esc(a["name"]))
            w("                required: %s," % ("true" if a.get("required") else "false"))
            w('                data_type: "%s",' % esc(a.get("data_type") or "xs:string"))
            w("                pattern: %s," % opt_str(a.get("pattern")))
            ev = a.get("enum_values") or []
            w("                enum_values: &[%s]," % ", ".join('"%s"' % esc(x) for x in ev))
            w("            },")
        w("        ],")
    if not groups:
        w("        choice_groups: &[],")
    else:
        w("        choice_groups: &[")
        for g in groups:
            w("            ChoiceGroup {")
            w("                min_occurs: %d," % int(g.get("min_occurs") or 0))
            w("                max_occurs: %s," % occurs(g.get("max_occurs")))
            w("                members: &[%s]," % ", ".join('"%s"' % esc(m) for m in g.get("children") or []))
            w("            },")
        w("        ],")
    w("        data_type: %s," % opt_str(resolve(h, "data_type")))
    w("        pattern: %s," % opt_str(resolve(h, "pattern")))
    ev = resolve(h, "enum_values") or []
    w("        enum_values: &[%s]," % ", ".join('"%s"' % esc(x) for x in ev))
    w("    },")
w("];")
w("")
w("/// Element names ISO 23387 declares as global document roots.")
w("pub(crate) static GLOBAL_ROOTS: &[(&str, usize)] = &[")
for r in roots:
    d = els.get(r) or {}
    target = d.get("data_type") if (d.get("data_type") in els) else r
    if target in index:
        w('    ("%s", %d),' % (esc(r), index[target]))
w("];")
w("")
pathlib.Path(OUT).write_text("\n".join(L) + "\n")
print("wrote", OUT, len(L), "lines")
